name: oldcity
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  card_swiper: ^3.0.1
  carousel_slider: ^5.0.0
  stacked_card_carousel: ^0.0.4
  url_launcher: ^6.3.1
  youtube_player_iframe: ^4.0.4

  
  
  blur: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true
  assets:
    - assets/old3.jpg
    - assets/ru.jpg
    - assets/bari.jpg
    - assets/chit.jpg
    - assets/ku.jpg
    - assets/assets2.jpg
    - assets/guru.webp
    - assets/images/
    - assets/movies.json
    - assets/ray_writings_sections.json
    - assets/feluda_books.json
    - assets/shonku_books.json

  